import { Routes } from '@angular/router';


export const routes: Routes = [
  { path: '', loadComponent: () => import('./home-rtih/home-rtih').then(m => m.HomeRtih) },
  { path: 'home', loadComponent: () => import('./home-rtih/home-rtih').then(m => m.HomeRtih) },
  { path: 'faqs', loadComponent: () => import('./faqs-main/faqs-main.component').then(m => m.FaqsMainComponent) },
  { path: 'contact', loadComponent: () => import('./contact-us/contact-us.component').then(m => m.ContactUsComponent) },
  { path: 'careers', loadComponent: () => import('./careers-rtih/careers-rtih.component').then(m => m.CareersRtihComponent) },
  { path: 'tenders', loadComponent: () => import('./tenders/tenders').then(m => m.Tenders) },
  // { path: 'RTIH-outpost-model', component: RtihOutpostModelComponent},
  //{ path: 'iih', component: IihComponent},
  { path: 'sidbi-seed-fund', redirectTo: 'funding-opportunities', pathMatch: 'full' },
  { path: 'avgc', redirectTo: 'avgc-xr', pathMatch: 'full' },
  { path: 'industrial-hackathon', redirectTo: 'hackathons-challenges', pathMatch: 'full' },
  { path: 'rural-innovators', redirectTo: 'grassroots-innovation', pathMatch: 'full' },
  { path: 'industrial-innovation', data: { breadcrumb: 'Industrial Innovation' },
  loadComponent: () => import('./iih/iih.component').then(m => m.IihComponent) },
  { path: 'about', data: { breadcrumb: 'About Us' },
  loadComponent: () => import('./about-rtih/about-rtih.component').then(m => m.AboutRtihComponent) },
  { path: 'programs', pathMatch: 'full', data: { breadcrumb: 'Programs' },
  loadComponent: () => import('./programms-rtih/programms-rtih.component').then(m => m.ProgrammsRtihComponent) },
  { path: 'incubation', data: { breadcrumb: 'Incubation', mode: 'main' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'programs/:programId', data: { breadcrumb: 'Program Track', mode: 'program' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'spark', data: { breadcrumb: 'SPARK', mode: 'program', programId: 'spark' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'future-founders', data: { breadcrumb: 'Future Founders', mode: 'program', programId: 'future-founders' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'catalyst', data: { breadcrumb: 'Catalyst', mode: 'program', programId: 'catalyst' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'velocity-lab', data: { breadcrumb: 'Velocity Lab', mode: 'program', programId: 'velocity-lab' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'medtech', data: { breadcrumb: 'MedTech Challenge', mode: 'program', programId: 'medtech' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'avgc-xr', data: { breadcrumb: 'AVGC-XR Incubation', mode: 'program', programId: 'avgc-xr' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'student-entrepreneurship', data: { breadcrumb: 'Student Entrepreneurship', mode: 'program', programId: 'student-entrepreneurship' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'climatetech', data: { breadcrumb: 'ClimateTech Cohort', mode: 'program', programId: 'climatetech' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'mobility', data: { breadcrumb: 'Mobility Cohort', mode: 'program', programId: 'mobility' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'foodtech', data: { breadcrumb: 'FoodTech Cohort', mode: 'program', programId: 'foodtech' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'evtech', data: { breadcrumb: 'EVTech Cohort', mode: 'program', programId: 'evtech' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'funding-opportunities', data: { breadcrumb: 'Funding Opportunities' },
  loadComponent: () => import('./sidbi/sidbi').then(m => m.Sidbi) },
  { path: 'startup-toolkit', data: { breadcrumb: 'Startup Toolkit', mode: 'toolkit' },
  loadComponent: () => import('./incubation-page/incubation-page.component').then(m => m.IncubationPageComponent) },
  { path: 'events', data: { breadcrumb: 'Events' },
  loadComponent: () => import('./events-rtih/events-rtih.component').then(m => m.EventsRtihComponent) },  
  { path: 'grassroots-innovation', data: { breadcrumb: 'Grassroots Innovation' },
  loadComponent: () => import('./grassroots-innovation/grassroots-innovation.component').then(m => m.GrassrootsInnovationComponent) },
  { path: 'hackathons-challenges', data: { breadcrumb: 'Hackathons & Challenges' },
  loadComponent: () => import('./hackthons-challanges/hackthons-challanges').then(m => m.HackthonsChallanges) },
  { path: 'location/:district', loadComponent: () => import('./spoke-rith/spoke-rith.component').then(m => m.SpokeRithComponent) },
  { path: 'sunrise-connects', data: { breadcrumb: 'sunrise-connects' },
  loadComponent: () => import('./sunrise-connects/sunrise-connects.component').then(m => m.SunriseConnectsComponent) },
  { path: 'healthtech-innovation-challenge-2025', data: { breadcrumb: 'sunrise-connects' },
  loadComponent: () => import('./health-tech-innovation/health-tech-innovation.component').then(m => m.HealthTechInnovationComponent) },
  { path: 'ed-tech-innovation', data: { breadcrumb: 'ed-tech-innovation' },
  loadComponent: () => import('./ed-tech-innovation/ed-tech-innovation.component').then(m => m.EdTechInnovationComponent) },
  { path: 'innotribe', data: { breadcrumb: 'InnoTribe' },
  loadComponent: () => import('./innotribe/innotribe').then(m => m.Innotribe) },
  // { path: 'iih', data: { breadcrumb: 'Industrial Innovation Hackathon' },
  // loadComponent: () => import('./industrial-innovation-hackathon/industrial-innovation-hackathon.component').then(m => m.IndustrialInnovationHackathonComponent) }, 
];
